# Server config
server:
  port: 9000
  ssl:
    enabled: true
    #client-auth: need
    key-store: classpath:gateway.p12
    key-store-password: password
    key-alias: gateway
    key-store-type: PKCS12
    trust-store: classpath:gateway.p12
    trust-store-password: password
    trust-store-type: PKCS12
  tomcat:
    accesslog:
      enabled: true
logging:
  level:
    org.springframework.security: DEBUG
spring:
  cloud:
    gateway:
# TODO: Work in progress, trying to set up mTLS between Gateway Service and Subscribe service
#      httpclient:
#        ssl:
#          trustedX509Certificates:
#            - classpath:subscription.crt
      routes:
        - id: subscription
          uri: http://localhost:9002
          predicates:
            - Path=/subscription/**

#client:
#  ssl:
#    one-way-authentication-enabled: false
#    two-way-authentication-enabled: true
#    key-store: gateway.p12
#    key-store-type: PKCS12
#    key-password: password
#    key-store-password: password
#    trust-store: gateway.p12
#    trust-store-password: password

