# Server config
server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: subscription
          uri: http://localhost:9002
          predicates:
            - Path=/subscription/**
        
